version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    user: ${USERID}:${GROUPID}
    ports:
      - ${HTTP_PORT}:${APP_PORT}
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
      ND_DEFAULTLANGUAGE: zh-Hans
      ND_ENABLEDOWNLOADS: false
      ND_DEFAULTTHEME: Light
      ND_AUTOIMPORTPLAYLISTS: false
    volumes:
      - ${DATA_PATH}:/data
      - ${MUSIC_DIR}:/music:ro
